##Necessary libraries and helper functions.##
library(tidyverse)
library(httr)
library(tictoc)
library(conflicted)
library(jsonlite)
library(RJSONIO)
library(geojsonR)
library(plotly)
library(scales)
