##Necessary libraries and helper functions.##
library(dplyr)
library(httr)
library(tictoc)
library(conflicted)
library(jsonlite)
library(RJSONIO)
library(geojsonR)
library(plotly)
library(scales)
library(readxl)
library(writexl)
library(stringr)
library(readr)
library(lubridate)